### ISSUE TITLE
Please add wheel package on PyPI

### ISSUE THREAD

**Issue by kamikaze** [cloudify-cosmo/cloudify-openstack-plugin#105]

**Comment by idanmo** [comment]
Hi,

We currently don't have plans for adding this plugin to the pypi repository.
Starting from Cloudify 3.3, we pack plugins as [wagons](https://github.com/cloudify-cosmo/wagon).
If you have any questions please join [Cloudify's users mailing list](https://groups.google.com/forum/#!forum/cloudify-users).

Regards,
Idan
