### ISSUE TITLE
hi，there ， how to use openstack plugin，the Usage didn't work 

### ISSUE THREAD

**Issue by zhangdavids** [cloudify-cosmo/cloudify-openstack-plugin#117]
anyone has awesome blog about it，seeking for help

**Comment by idanmo** [comment]
Hi,

Thanks for trying Cloudify!
Please use this Google group for assistance: https://groups.google.com/forum/#!forum/cloudify-users
And please describe which version of Cloudify you are using.
You can find a basic OpenStack example here:
https://github.com/cloudify-cosmo/cloudify-hello-world-example/blob/3.3.1/blueprint.yaml

Regards,
Idan
