### ISSUE TITLE
Cloudify compoer fails to import openstack types

### ISSUE THREAD

**Issue by thomnico** [cloudify-cosmo/cloudify-openstack-plugin#159]
Cloudify composer can not import openstack types .. complaining that plugin can not be parsed.

Tried 2.0.1 and b3.1 without success

**Comment by idanmo** [comment]
Hi,

The issue is caused by a duplicate description key in the plugin.yaml file.
A fix was already merged to `master` branch so you can try importing from `master`.

The next release of the plugin will include the fix.

**Comment by thomnico** [comment]
Tried git pull from master .. zip and import ... same error : can not parse input
