### ISSUE TITLE
Patch to Backport Keystone v3 Support to Plugin Version 1.2.1

### ISSUE THREAD

**Issue by EarthmanT** [cloudify-cosmo/cloudify-openstack-plugin#215]
[This commit](https://github.com/cloudify-cosmo/cloudify-openstack-plugin/commit/33be96f4c25c8a56ef391226297dee82e9364d7e) contains the v3 support.

Please create a patch to backport these changes to the v1.2.1 base. It needs to apply on a 4.3 Manager that has been restored from 3.4.2 snapshot, that was restored from 3.2.1 Snapshot.

**Comment by mabuaisha** [comment]
@EarthmanT I think is done and can be closed , what do you think ?

**Comment by EarthmanT** [comment]
Done
