### ISSUE TITLE
Instance is loosing FIP after HEAL workflow execution.

### ISSUE THREAD

**Issue by astianseb** [cloudify-cosmo/cloudify-openstack-plugin#235]
When running HEAL workflow on instance which have floating IP's, plugin is detaching  them at "port detach" but not reassigning them on "attach". As a result, instance after HEAL workflow is loosing FIP

**Comment by EarthmanT** [comment]
Fixed in #240 #241 [v2.9.0](https://github.com/cloudify-cosmo/cloudify-openstack-plugin/releases/tag/2.9.0).
