### ISSUE TITLE
plugin installation fails.

### ISSUE THREAD

**Issue by SiavashSardari** [cloudify-cosmo/cloudify-openstack-plugin#242]
The latest version of cmd2 requires Python3.4 or above. this cause installation failure.

Collecting cmd2>=0.6.7 (from cliff!=1.16.0,!=1.17.0,>=1.15.0->python-neutronclient==6.0.0->cloudify-openstack-plugin==2.9.0)
  Using cached https://files.pythonhosted.org/packages/07/4a/f8c16175fa806b9c81f60688411b09a84a23decf774f2cdd5657e43dfe9b/cmd2-0.9.0.post1.tar.gz
cmd2 requires Python '>=3.4' but the running Python is 2.7.14

**Comment by EarthmanT** [comment]
Cloudify products are not currently compatible with Python 3.
