### ISSUE TITLE
`availability_zone` not present as volume's runtime property

### ISSUE THREAD

**Issue by rajalokan** [cloudify-cosmo/cloudify-openstack-plugin#255]
I'm trying to boot an openstack instance using an existing openstack volume resource. While running the blueprint I get an error similar to 
`KeyError: 'availability_zone'`. 

This is because of like  `az = boot_volume.runtime_properties[OPENSTACK_AZ_PROPERTY]`   at https://github.com/cloudify-cosmo/cloudify-openstack-plugin/blob/073922b8419a1f37aad67aee0cd89e7019b0b4f6/nova_plugin/server.py#L229 

Looking at runtime properties of volume, I see `availability_zone` isn't at top level.  Rather it is stored under key `external_resource`. 

For now in my openstack plugin source code, when I change the above line to 
`az = boot_volume.runtime_properties['external_resource'][OPENSTACK_AZ_PROPERTY]` I can get this working. 

Can you please suggest what changes needs to be done in blueprint to make sure I don't have to patch cloudify-openstack-plugin source. 

My sample blueprint is:
```node_templates:

  host:
    type:  cloudify.openstack.nodes.Server
    properties:
      openstack_config: *openstack_config
      resource_id:  XXX
      flavor: XXX
      management_network_name: XXX
    relationships:
      - type: cloudify.openstack.volume_attached_to_server
        target: volume

  volume:
    type: cloudify.openstack.nodes.Volume
    properties:
      openstack_config: *openstack_config
      boot: true
      resource_id: XXX
      use_external_resource: true
```

**Comment by EarthmanT** [comment]
Hello,
Sorry that we did not catch that error! Apparently, this attribute was not set correctly when setting `use_external_resource: true`.
I have provided a fix in the code that is more consistent and added a test for the use case.
Please find the fix in the linked [new version](https://github.com/cloudify-cosmo/cloudify-openstack-plugin/releases/tag/2.9.6).
Thanks for reaching out!
