### ISSUE TITLE
Can't find a consistent set of dependencies

### ISSUE THREAD

**Issue by dimbleby** [cloudify-cosmo/cloudify-openstack-plugin#265]
This project [insists](https://github.com/cloudify-cosmo/cloudify-openstack-plugin/blob/0079b863d10d551c738ef5b53188292bd0da5358/setup.py#L37) on `keystoneauth1<3`.

This conflicts with the requirements of `os-client-config` and `osc-lib` (via `python-neutronclient`), and also `openstacksdk` (via `osc-lib`) - which variously require `keystoneauth1>=3.7.0` or `keystoneauth1>=3.8.0`.

`pipenv`, at least, is unable to find a set of packages that satisfies everyone's requirements.

Can the requirement on `keystoneauth1<3` be relaxed?  (Does there exist some solution to all of these constraints that `pipenv` - and I! - have failed to find?)

**Comment by mabuaisha** [comment]
@dimbleby We released new version https://github.com/cloudify-cosmo/cloudify-openstack-plugin/releases/tag/2.12.1 that fix the issue `keystoneauth` please check it and let us know what do you think https://github.com/cloudify-cosmo/cloudify-openstack-plugin/commit/ad8e31452b0f7127bb656dcdc2723fd30a008756

**Comment by dimbleby** [comment]
thanks, yes, this version appears to be soluble!
