### ISSUE TITLE
Static routes in neutron router are not supported

### ISSUE THREAD

**Issue by astianseb** [cloudify-cosmo/cloudify-openstack-plugin#266]
Not possible to add static routes to existing router

**Comment by astianseb** [comment]
#

**Comment by thomnico** [comment]
I second this big time as I have an urgent need for it. Tried several methods with an interface to add it once created. 
In addition it does not work at creation either.

**Comment by mabuaisha** [comment]
@thomnico we already added support for static route as and it can be added using one of the following options:
1. Static route node type ---> check this blueprint https://github.com/cloudify-cosmo/cloudify-openstack-plugin/blob/master/blueprints/routes.yaml

2. Using cloudify relationship on establish operation . ---> check this blueprint https://github.com/cloudify-cosmo/cloudify-openstack-plugin/blob/master/blueprints/router.yaml#L104

3. You can also  update routes by running `cfy executions start execute_operation` for `update ` operation https://github.com/cloudify-cosmo/cloudify-openstack-plugin/blob/master/plugin.yaml#L641

**Comment by EarthmanT** [comment]
#267
