### ISSUE TITLE
Human redable error output

### ISSUE THREAD

**Issue by Vladimir-Antonovich** [cloudify-cosmo/cloudify-openstack-plugin#283]
When OpenStack fails to create a new server, we get the following error in the logs:

NonRecoverableError: Unexpected server state ERROR:None

However, this doesn't actually give the operator any idea as to what the problem is. Instead, an operator must log onto their OpenStack rig and look at the server in question. In this case, the fault message in OpenStack was 'No valid host was found. There are not enough hosts available.'

It would be useful for Cloudify to expose the fault message so that operators don't always need to go digging in their OpenStack rig.

Logs are available by link https://cloudify-cs.atlassian.net/wiki/download/attachments/597688326/cloudify-manager-logs_20181113T102551_localhost.tar.gz?api=v2 . 'oliver23' is the deployment name.

**Comment by Vladimir-Antonovich** [comment]
Logs provided to Trammell directly.

**Comment by abramso** [comment]
@EarthmanT Any ETA on this?
